import type {Metadata} from "next";
import {
    Cal_Sans,
    Geist,
    Geist_Mono,
    IBM_Plex_Sans,
    Inter,
    Inter_Tight, Manrope,
    Nunito,
    Nunito_Sans,
    Plus_Jakarta_Sans
} from "next/font/google";
import "./globals.scss";

const interTight = Inter({
    variable: "--font-inter-tight-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Petar Marković | Frontend Developer",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${interTight.variable} ${geistMono.variable} antialiased`}>
        <main className={"w-[768px] mx-auto max-[769px]:w-[90%]"}>
            {children}
        </main>
        </body>
        </html>
    );
}
